{
 "title": "Solar Production",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_power{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Energy Produced Today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watt_hours_today" }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reported_watts" }
   ]
  },
  {
   "title": "Net Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(active_power{type=\"production\"}[1m]))",
     "legendFormat": "Net"
    }
   ]
  },
  {
   "title": "Power Variation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(active_power{type=\"production\"}[5m])) - sum(avg_over_time(active_power{type=\"production\"}[5m] offset 1d))",
     "legendFormat": "-1d"
    },
    {
     "expr": "sum(avg_over_time(active_power{type=\"production\"}[5m])) - sum(avg_over_time(active_power{type=\"production\"}[5m] offset 1w))",
     "legendFormat": "-1w"
    },
    {
     "expr": "sum(avg_over_time(active_power{type=\"production\"}[5m])) - sum(avg_over_time(active_power{type=\"production\"}[5m] offset 30d))",
     "legendFormat": "-30d"
    },
    {
     "expr": "sum(avg_over_time(active_power{type=\"production\"}[5m])) - sum(avg_over_time(active_power{type=\"production\"}[5m] offset 1y))",
     "legendFormat": "-1y"
    }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(reported_watts[10s])",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "24 Hour Power Variation by Inverter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(reported_watts[1m]) - avg_over_time(reported_watts[1m] offset 1d)",
     "legendFormat": "{{serial_number}}"
    }
   ]
  }
 ]
}