apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enphase-prometheus
  name: enphase-prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enphase-prometheus
  template:
    metadata:
      labels:
        app: enphase-prometheus
    spec:
      containers:
      - env:
        - name: ENVOY_URL
          value: "http://192.168.1.125"
        - name: ARRAY_LAYOUT
          value: '{"system_id":2335303,"rotation":0,"dimensions":{"x_min":30,"x_max":430,"y_min":0,"y_max":700},"arrays":[{"array_id":3871525,"label":"array 1","x":230,"y":350,"azimuth":270,"modules":[{"module_id":48968985,"rotation":0,"x":300,"y":100,"inverter":{"inverter_id":51116942,"serial_num":"482125061710"}},{"module_id":48968986,"rotation":0,"x":200,"y":100,"inverter":{"inverter_id":51116946,"serial_num":"482125061458"}},{"module_id":48968987,"rotation":0,"x":100,"y":100,"inverter":{"inverter_id":51116938,"serial_num":"482125062528"}},{"module_id":48968988,"rotation":0,"x":0,"y":100,"inverter":{"inverter_id":51116956,"serial_num":"482125062558"}},{"module_id":48968989,"rotation":0,"x":-100,"y":100,"inverter":{"inverter_id":51116940,"serial_num":"482125062554"}},{"module_id":48968990,"rotation":0,"x":-200,"y":100,"inverter":{"inverter_id":51116933,"serial_num":"202117037990"}},{"module_id":48968991,"rotation":0,"x":-300,"y":100,"inverter":{"inverter_id":51116932,"serial_num":"482125062686"}},{"module_id":48968992,"rotation":0,"x":300,"y":-100,"inverter":{"inverter_id":51116950,"serial_num":"482125061240"}},{"module_id":48968993,"rotation":0,"x":200,"y":-100,"inverter":{"inverter_id":51116948,"serial_num":"482125062610"}},{"module_id":48968994,"rotation":0,"x":100,"y":-100,"inverter":{"inverter_id":51116952,"serial_num":"482125061975"}},{"module_id":48968995,"rotation":0,"x":0,"y":-100,"inverter":{"inverter_id":51116949,"serial_num":"482125062650"}},{"module_id":48968996,"rotation":0,"x":-100,"y":-100,"inverter":{"inverter_id":51116944,"serial_num":"482125061455"}},{"module_id":48968997,"rotation":0,"x":-200,"y":-100,"inverter":{"inverter_id":51116936,"serial_num":"482125061677"}},{"module_id":48968998,"rotation":0,"x":-300,"y":-100,"inverter":{"inverter_id":51116935,"serial_num":"482125062378"}}],"dimensions":{"x_min":30,"x_max":430,"y_min":0,"y_max":700},"tilt":20,"array_type_name":"","pcu_count":14,"pv_module_details":{"manufacturer":"SunSpark","model":"SST-320M3B","type":null,"power_rating":null}}],"haiku":"Put upon the roof / I am waiting for the sun / All I see is clouds"}'
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: envoy-credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: envoy-credentials
              key: password
        image: mystik738/enphase-prometheus:0.6
        name: enphase-prometheus
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
        resources:
          limits:
            cpu: 80m
            memory: 40Mi
          requests:
            cpu: 40m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enphase-prometheus
  name: enphase-prometheus
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 8099
    targetPort: 80
    protocol: TCP
  selector:
    app: enphase-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enphase-prometheus-sm
  namespace: monitoring
  labels:
    app: enphase-prometheus
spec:
  selector:
    matchLabels:
      app: enphase-prometheus
  endpoints:
  - port: metrics 
    targetPort: 8099
    interval: 10s   
    honorLabels: true
    metricRelabelings:
    - action: labeldrop
      regex: instance
    - action: labeldrop
      regex: pod